print("HELLO WORLD!")
print("HELLO Again")
print("I like typing this.")
print("This is fun.")
print('Yay! Printing.')
print("I'd much rather you n'ut'.")
print('I "said" do not touch this.')
print("is the number sign so ....... i mean ......... huh maaaan ... i how should i say this .... it does not work.")